<a href="https://colab.research.google.com/github/dileep9968/pytorch/blob/main/00_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


# Introduction to tensor
Creating tensors

In [ ]:
# Scalers
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tenors
Why random tensor?
Random tenosrs are important the way many neural networks lean they start with tenosr full of random number and adjust those random number to better represention the data.

In [ ]:
# Create a random tenosr of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1461, 0.0233, 0.2935, 0.1483],
        [0.6910, 0.6059, 0.5616, 0.7383],
        [0.9185, 0.2657, 0.6556, 0.6441]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tenosr with similar shape to an image tensor
randam_image_size_tenosr = torch.rand(size=(224,224,3)) # height, width, color channel
randam_image_size_tenosr.shape, randam_image_size_tenosr.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and ones

In [ ]:
# Creae a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tenosr of all
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tenosr and tensor-like

In [ ]:
#use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.5.0+cu121'

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensor like
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tenosr  = float_32_tensor.type(torch.float16)
float_16_tenosr
#

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tenosr*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting informaito form tensors



In [ ]:
# create a tenosr
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4831, 0.7934, 0.3258, 0.6497],
        [0.7456, 0.7276, 0.7232, 0.0611],
        [0.1781, 0.6430, 0.5833, 0.3109]])

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tenosr.device}")

tensor([[0.4831, 0.7934, 0.3258, 0.6497],
        [0.7456, 0.7276, 0.7232, 0.0611],
        [0.1781, 0.6430, 0.5833, 0.3109]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Mulitpulation tensor
Tensor opertions include:
* Addition
* Substraction
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +5

tensor([6, 7, 8])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [ ]:
torch.add(tensor,5)

tensor([6, 7, 8])

### Matrix multiplicaiton

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

### One if the most common erros in deep learning: Shape Error

In [4]:
# Shapes for matric multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [4,5]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [5]:
# tensor shape issue, we can maniplute the shape of one of our tenosr
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [6]:
torch.mm(tensor_A,tensor_B.T)

tensor([[27, 30, 33],
        [61, 68, 75],
        [78, 87, 96]])

### Finding the min, max, mean, sum

In [7]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
torch.min(x),x.max()

(tensor(0), tensor(90))

In [9]:
x.max()

tensor(90)

In [10]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [11]:
x.dtype

torch.int64

In [13]:
# torch.mean() function requires a tensor of float32 datatypoe
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [14]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the position min and max

In [15]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
x.argmin()

tensor(0)

In [18]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing

In [19]:
x = torch.arange(1.,10.)

In [20]:
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [21]:
# adding an extra dimension which comptiable with input size
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
# Change the view
# Chaing z changes x (because a view of tenose share the same memory of original)
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
# stack tensor on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0) # dim is hstack
x_stacked


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [27]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [28]:
x.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
x_reshaped = x.reshape(1,1,9)
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [32]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
# torch.unsqueeze() add a single dimension to a target tensor
x_reshaped

tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [36]:
x = torch.randn(size=(224,224,3))
# permute the origin x
x_permuted = x.permute(2,0,1) # shits axis 0->1,1->2,2->0
x_permuted.shape

torch.Size([3, 224, 224])

### Indexin similar to numpy

In [37]:
# create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [38]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
x[0][0]

tensor([1, 2, 3])

In [41]:
x[0][0].ndim

1

In [42]:
x[0][0][0]

tensor(1)

In [43]:
x[:,0]

tensor([[1, 2, 3]])

In [44]:
x[:,:,1]

tensor([[2, 5, 8]])

In [48]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [49]:
# change the value of array what will this do to tenso
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [50]:
# Tensor to numpy assray
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility ( trying to take random out of random)

In [55]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6832, 0.1586, 0.6421, 0.0245],
        [0.3414, 0.4290, 0.0414, 0.0743],
        [0.2687, 0.3647, 0.2631, 0.1007]])
tensor([[0.9733, 0.5268, 0.0562, 0.6283],
        [0.2328, 0.8835, 0.9615, 0.5553],
        [0.5016, 0.0226, 0.4186, 0.6565]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [56]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensor and pytorch object on the GPU

In [4]:
!nvidia-smi

Wed Nov 13 07:47:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
# check for GPU access with torch
import torch
torch.cuda.is_available()

True

In [6]:
# Setup device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [7]:
# coiunt the no of gpu
torch.cuda.device_count()

1

In [8]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [12]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')