<a href="https://colab.research.google.com/github/dileep9968/pytorch/blob/main/00_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.0+cu121


# Introduction to tensor
Creating tensors

In [ ]:
# Scalers
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tenors
Why random tensor?
Random tenosrs are important the way many neural networks lean they start with tenosr full of random number and adjust those random number to better represention the data.

In [ ]:
# Create a random tenosr of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1461, 0.0233, 0.2935, 0.1483],
        [0.6910, 0.6059, 0.5616, 0.7383],
        [0.9185, 0.2657, 0.6556, 0.6441]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tenosr with similar shape to an image tensor
randam_image_size_tenosr = torch.rand(size=(224,224,3)) # height, width, color channel
randam_image_size_tenosr.shape, randam_image_size_tenosr.ndim

(torch.Size([224, 224, 3]), 3)

### Zero and ones

In [ ]:
# Creae a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tenosr of all
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tenosr and tensor-like

In [ ]:
#use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.5.0+cu121'

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensor like
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None,
                               device=None,
                               requires_grad=False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tenosr  = float_32_tensor.type(torch.float16)
float_16_tenosr
#

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tenosr*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting informaito form tensors



In [ ]:
# create a tenosr
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4831, 0.7934, 0.3258, 0.6497],
        [0.7456, 0.7276, 0.7232, 0.0611],
        [0.1781, 0.6430, 0.5833, 0.3109]])

In [ ]:
some_tensor.size()

torch.Size([3, 4])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tenosr.device}")

tensor([[0.4831, 0.7934, 0.3258, 0.6497],
        [0.7456, 0.7276, 0.7232, 0.0611],
        [0.1781, 0.6430, 0.5833, 0.3109]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Mulitpulation tensor
Tensor opertions include:
* Addition
* Substraction
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +5

tensor([6, 7, 8])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor -10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,5)

tensor([ 5, 10, 15])

In [ ]:
torch.add(tensor,5)

tensor([6, 7, 8])

### Matrix multiplicaiton

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
### One