<a href="https://colab.research.google.com/github/dileep9968/pytorch/blob/main/into_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [1]:
#!pip list

### Tensors

In [2]:
import torch
import numpy as np

In [ ]:
np1 =np.random.rand(3,4)
np1

array([[0.84755523, 0.90623194, 0.49858654, 0.89531758],
       [0.10060489, 0.07256085, 0.04657411, 0.08820269],
       [0.25438601, 0.41089902, 0.265184  , 0.76281681]])

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.8806, 0.4723, 0.2406, 0.5115],
        [0.2254, 0.4262, 0.3494, 0.4581],
        [0.3616, 0.6228, 0.4553, 0.5326]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# ceate tensor out of numpy array
my_tensor  = torch.tensor(np1)
my_tensor

tensor([[0.8476, 0.9062, 0.4986, 0.8953],
        [0.1006, 0.0726, 0.0466, 0.0882],
        [0.2544, 0.4109, 0.2652, 0.7628]], dtype=torch.float64)

In [ ]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and view
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items using -1
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Difference between view and reshape. view work on continou memory location and reshape work on both continou and non-continous

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [4]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
# substract
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
# sub fuction
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [8]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
# mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
# division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [16]:
## Exponents or power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [17]:
tensor_a

tensor([1, 2, 3, 4])

In [18]:
tensor_b

tensor([5, 6, 7, 8])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [21]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([1, 2, 3, 4])

In [23]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a

tensor([ 6,  8, 10, 12])